<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,17,1,'5Lqn5ZOB5Lit5b+D');
$cfg_Cs[2]=array(0,1,1,'5YWz5LqO5oiR5Lus');
$cfg_Cs[3]=array(0,1,1,'5paw6Ze75Lit5b+D');
$cfg_Cs[4]=array(0,1,1,'5Zyo57q/6K6i6LSt');
$cfg_Cs[5]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[6]=array(3,1,1,'5LyB5Lia5paw6Ze7');
$cfg_Cs[7]=array(3,1,1,'6KGM5Lia5paw6Ze7');
$cfg_Cs[8]=array(3,1,1,'5Lqn5ZOB55+l6K+G');
$cfg_Cs[9]=array(1,17,1,'56Oo57KJ6K6+5aSH');
$cfg_Cs[10]=array(1,17,1,'56C056KO6K6+5aSH');
?>