<field:jinliao itemname="进料粒度" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:jinliao>
<field:chengpin itemname="成品细度" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:chengpin>
<field:chanliang itemname="成品产量" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:chanliang>
<field:jiagong itemname="物料加工" autofield="1" notsend="0" type="text" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:jiagong>
<field:body itemname="内容" autofield="1" notsend="0" type="htmltext" isnull="true" islist="1" default=""  maxlength="250" page="">
</field:body>
