<?php
$z[0]=Array("channel"," <a href='[field:typeurl/]' 0 title='[field:typename/]'>[field:typename/]</a><span>|</span> ",35,175);
$z[0][4]['type']="top";
$z[0][4]['row']="5";
$z[1]=Array("type"," <a href='[field:typelink/]'  title='[field:typename/]'>[field:typename/]</a><span>|</span> ",181,308);
$z[1][4]['typeid']="16";
$z[2]=Array("type"," <a href='[field:typelink/]'  title='[field:typename/]'>[field:typename/]</a> ",314,426);
$z[2][4]['typeid']="5";
$z[3]=Array("global","",469,495);
$z[3][4]['name']="cfg_powerby";
$z[4]=Array("global","",496,520);
$z[4][4]['name']="cfg_beian";

?>