<?php
$z[0]=Array("global","",87,113);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",155,181);
$z[1][4]['name']="cfg_webname";
$z[2]=Array("global","",190,216);
$z[2][4]['name']="cfg_webname";
$z[3]=Array("type","\r\n        <li id='nav_7' style='width:122px;' ><a href='[field:typelink/]' 0 title='[field:typename/]' class='hover-none nav'><span>[field:typename/]</span></a></li>\r\n        ",856,1065);
$z[3][4]['typeid']="2";
$z[4]=Array("type","\r\n        <li id='nav_2' style='width:122px;' ><a href='[field:typelink/]'  title='[field:typename/]' class='hover-none nav'><span>[field:typename/]</span></a></li>\r\n        ",1107,1315);
$z[4][4]['typeid']="6";
$z[5]=Array("type","\r\n        <li id='nav_4' style='width:122px;' ><a href='[field:typelink/]'  title='[field:typename/]' class='hover-none nav'><span>[field:typename/]</span></a></li>\r\n        ",1357,1565);
$z[5][4]['typeid']="9";
$z[6]=Array("type","\r\n        <li id='nav_19' style='width:121px;' ><a href='[field:typelink/]'  title='[field:typename/]' class='hover-none nav'><span>[field:typename/]</span></a></li>\r\n        ",1607,1817);
$z[6][4]['typeid']="16";
$z[7]=Array("type","\r\n        <li id='nav_21' style='width:121px;' ><a href='[field:typelink/]'  title='[field:typename/]' class='hover-none nav'><span>[field:typename/]</span></a></li>\r\n        ",1859,2069);
$z[7][4]['typeid']="17";
$z[8]=Array("type","\r\n        <li id='nav_29' style='width:121px;' ><a href='[field:typelink/]'  title='[field:typename/]' class='hover-none nav'><span>[field:typename/]</span></a></li>\r\n        ",2111,2321);
$z[8][4]['typeid']="20";
$z[9]=Array("type","\r\n        <li id='nav_8' style='width:121px;' ><a href='[field:typelink/]'  title='[field:typename/]' class='hover-none nav'><span>[field:typename/]</span></a></li>\r\n        ",2363,2571);
$z[9][4]['typeid']="5";

?>