<?php
$z[0]=Array("global","",66,92);
$z[0][4]['name']="cfg_webname";
$z[1]=Array("global","",136,166);
$z[1][4]['name']="cfg_description";
$z[2]=Array("global","",203,230);
$z[2][4]['name']="cfg_keywords";
$z[3]=Array("include","",675,710);
$z[3][4]['filename']="head.htm";
$z[4]=Array("type"," <a href=\"[field:typelink/]\"title=\"[field:typename/]\" class=\"more fr\"></a>",1142,1250);
$z[4][4]['typeid']="9";
$z[5]=Array("arclist","\r\n            <li class='list'><a href='[field:arcurl/]' title='[field:title/]' target='_self' class='img'><img src='[field:picname/]' alt='[field:title/]' title='[field:title/]' width='223' height='180' /></a>\r\n              <h3 style='width:223px;'><a href='[field:arcurl/]' title='[field:title/]' target='_self'>[field:title/]</a></h3>\r\n            </li>\r\n            ",1644,2074);
$z[5][4]['typeid']="9";
$z[5][4]['row']="14";
$z[5][4]['titlelen']="12";
$z[6]=Array("flink","\r\n        <li>[field:link /] </li>\r\n        ",2381,2485);
$z[6][4]['titlelen']="20";
$z[6][4]['row']="20";
$z[6][4]['type']="text";
$z[7]=Array("channel"," <a href='[field:typeurl/]' 0 title='[field:typename/]'>[field:typename/]</a><span>|</span> ",2594,2734);
$z[7][4]['type']="top";
$z[7][4]['row']="5";
$z[8]=Array("type"," <a href='[field:typelink/]'  title='[field:typename/]'>[field:typename/]</a><span>|</span> ",2740,2867);
$z[8][4]['typeid']="16";
$z[9]=Array("type"," <a href='[field:typelink/]'  title='[field:typename/]'>[field:typename/]</a> ",2873,2985);
$z[9][4]['typeid']="5";
$z[10]=Array("global","",3028,3054);
$z[10][4]['name']="cfg_powerby";
$z[11]=Array("global","",3055,3079);
$z[11][4]['name']="cfg_beian";

?>